### ISSUE TITLE
Minigames Daily/Weekly/Monthly Rewards Glitch

### ISSUE THREAD

**Issue by WitherPlayMc** [Eternal-Craft/Server#6]
You can visit the villager every day and recieve all the rewards even thugh 1 month or week didn't pass yet.

This problem could be the data not being saved and the timer resets every restart / etc

**Comment by aj5720** [comment]
This needs to bee fixed though ASAP
Players are complaining the increase of the players with Penguin/Cop kits in KitPVP

**Comment by ZeeKingEpic** [comment]
Its Disabled ATM until we Fix it ;)
